// <auto-generated />
using System;
using Kakeibo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kakeibo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503045128_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kakeibo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsIncome")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Kakeibo.Models.Monthly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Fuku")
                        .HasColumnType("integer");

                    b.Property<int>("Gaishokuhi")
                        .HasColumnType("integer");

                    b.Property<int>("Kootsuuhi")
                        .HasColumnType("integer");

                    b.Property<int>("Koutsuuhi")
                        .HasColumnType("integer");

                    b.Property<int>("Kyuuryo")
                        .HasColumnType("integer");

                    b.Property<int>("Nichiyouhin")
                        .HasColumnType("integer");

                    b.Property<int>("Shokuhi")
                        .HasColumnType("integer");

                    b.Property<int>("Shoseki")
                        .HasColumnType("integer");

                    b.Property<int>("Shuusi")
                        .HasColumnType("integer");

                    b.Property<int>("SonotaShishutsu")
                        .HasColumnType("integer");

                    b.Property<int>("SonotaShuunyuu")
                        .HasColumnType("integer");

                    b.Property<int>("Subscription")
                        .HasColumnType("integer");

                    b.Property<int>("Suidouhi")
                        .HasColumnType("integer");

                    b.Property<int>("Yatin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Monthlies");
                });

            modelBuilder.Entity("Kakeibo.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Kakeibo.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
